spring:
    jpa: null
    datasource:
        username: root
        password: root
        initialize: true
        jdbc-url: 'jdbc:mysql://localhost:3306/support_sys?createDatabaseIfNotExist=true'
        driver-class-name: com.mysql.cj.jdbc.Driver
hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: true
    format_sql: true
    id:
        new_generator_mappings: false
server:
    port: 8080
    servlet:
      context-path: /support
email:
    sendemail: true
    fromemail: email@gmail.com
    password: Password
