INSERT INTO "TOOL_INFO"("TOOL_ID","CREATED_BY","EMAIL_CONTACT","PORT","ROW_CREATED","TOOL_IP","TOOL_NAME") VALUES (1,'jakash','heroakashjain@gmail.com',8080,NULL,1,'taas');
INSERT INTO "ISSUE_STATUS_INFO"("STATUS_ID","ROW_CREATED","STATUS_NAME") VALUES (100001,null,'NEW');
INSERT INTO "ISSUE_STATUS_INFO"("STATUS_ID","ROW_CREATED","STATUS_NAME") VALUES (100002,null,'FIXED');
INSERT INTO "ISSUE_STATUS_INFO"("STATUS_ID","ROW_CREATED","STATUS_NAME") VALUES (100003,null,'USER_ERROR');
INSERT INTO "ISSUE_STATUS_INFO"("STATUS_ID","ROW_CREATED","STATUS_NAME") VALUES (100004,null,'CLOSED');
INSERT INTO "ISSUE_STATUS_INFO"("STATUS_ID","ROW_CREATED","STATUS_NAME") VALUES (100005,null,'NOT_A_BUG');